# ============================================
# ThreePointTurn 三点掉头参数配置示例
# ============================================
#
# 此文件提供了不同车型的ThreePointTurn参数配置示例。
# 使用时请根据实际车型选择对应的配置段。
#
# 配置方法：
# 1. 将对应的配置复制到导航参数文件中
# 2. 或者直接替换 three_point_turn_recoveries.yaml 的内容
# 3. 重新启动导航系统使配置生效
#

# ============================================
# Mini系列 - 小型阿克曼机器人
# ============================================
# 轴距：0.3-0.4米
# 特点：体积小，转向灵活
three_point_turn_recoveries_mini_akm:
  ros__parameters:
    # 阿克曼小车参数
    wheelbase: 0.35               # 轴距（米）
    max_steering_angle: 0.55      # 最大转向角（弧度，约31.5度）

    # 运动参数
    min_linear_vel: 0.08          # 最小线速度（m/s）
    linear_acc_lim: 0.4           # 线加速度限制（m/s²）
    steering_angle_velocity: 1.2  # 转向角速度（rad/s）

    # 安全参数
    simulate_ahead_time: 1.5      # 前瞻模拟时间（秒）

# 行为树参数建议：
# forward_dist="0.5" backward_dist="0.7" max_speed="0.4" max_steering_angle="0.55"

# ============================================
# Senior系列 - 中型阿克曼机器人
# ============================================
# 轴距：0.5-0.6米
# 特点：标准尺寸，平衡性能
three_point_turn_recoveries_senior_akm:
  ros__parameters:
    # 阿克曼小车参数
    wheelbase: 0.5                # 轴距（米）
    max_steering_angle: 0.5       # 最大转向角（弧度，约28.6度）

    # 运动参数
    min_linear_vel: 0.1           # 最小线速度（m/s）
    linear_acc_lim: 0.5           # 线加速度限制（m/s²）
    steering_angle_velocity: 1.0  # 转向角速度（rad/s）

    # 安全参数
    simulate_ahead_time: 2.0      # 前瞻模拟时间（秒）

# 行为树参数建议：
# forward_dist="0.75" backward_dist="1.0" max_speed="0.5" max_steering_angle="0.5"

# ============================================
# Top系列（带悬挂）- 大型阿克曼机器人
# ============================================
# 轴距：0.6-0.7米
# 特点：体积大，带悬挂系统
three_point_turn_recoveries_top_akm_bs:
  ros__parameters:
    # 阿克曼小车参数
    wheelbase: 0.65               # 轴距（米）
    max_steering_angle: 0.45      # 最大转向角（弧度，约25.8度）

    # 运动参数
    min_linear_vel: 0.12          # 最小线速度（m/s）
    linear_acc_lim: 0.6           # 线加速度限制（m/s²）
    steering_angle_velocity: 0.8  # 转向角速度（rad/s）

    # 安全参数
    simulate_ahead_time: 2.5      # 前瞻模拟时间（秒）

# 行为树参数建议：
# forward_dist="1.0" backward_dist="1.5" max_speed="0.6" max_steering_angle="0.45"

# ============================================
# Top系列（不带悬挂）- 大型阿克曼机器人
# ============================================
# 轴距：0.6-0.7米
# 特点：体积大，无悬挂系统
three_point_turn_recoveries_top_akm_dl:
  ros__parameters:
    # 阿克曼小车参数
    wheelbase: 0.65               # 轴距（米）
    max_steering_angle: 0.45      # 最大转向角（弧度，约25.8度）

    # 运动参数
    min_linear_vel: 0.12          # 最小线速度（m/s）
    linear_acc_lim: 0.6           # 线加速度限制（m/s²）
    steering_angle_velocity: 0.8  # 转向角速度（rad/s）

    # 安全参数
    simulate_ahead_time: 2.5      # 前瞻模拟时间（秒）

# 行为树参数建议：
# forward_dist="1.0" backward_dist="1.5" max_speed="0.6" max_steering_angle="0.45"

# ============================================
# 狭窄空间配置 - 适用于空间受限的环境
# ============================================
# 特点：减小转弯半径，减小运动距离
three_point_turn_recoveries_narrow_space:
  ros__parameters:
    # 阿克曼小车参数
    wheelbase: 0.5                # 轴距（米）
    max_steering_angle: 0.6       # 增大转向角以减小转弯半径

    # 运动参数
    min_linear_vel: 0.08          # 减小最小速度，更精确控制
    linear_acc_lim: 0.3           # 减小加速度，更平滑
    steering_angle_velocity: 1.5  # 增加转向速度

    # 安全参数
    simulate_ahead_time: 1.0      # 减小前瞻时间，更灵活

# 行为树参数建议：
# forward_dist="0.4" backward_dist="0.6" max_speed="0.3" max_steering_angle="0.6"

# ============================================
# 开阔空间配置 - 适用于空间充足的环境
# ============================================
# 特点：增大运动距离，提高执行效率
three_point_turn_recoveries_open_space:
  ros__parameters:
    # 阿克曼小车参数
    wheelbase: 0.5                # 轴距（米）
    max_steering_angle: 0.5       # 标准转向角

    # 运动参数
    min_linear_vel: 0.12          # 增大最小速度
    linear_acc_lim: 0.7           # 增大加速度，更快响应
    steering_angle_velocity: 1.2  # 增加转向速度

    # 安全参数
    simulate_ahead_time: 3.0      # 增大前瞻时间，更安全

# 行为树参数建议：
# forward_dist="1.0" backward_dist="1.5" max_speed="0.7" max_steering_angle="0.5"

# ============================================
# 保守配置 - 优先安全和平滑
# ============================================
# 特点：低速平滑运行，适合精确控制
three_point_turn_recoveries_conservative:
  ros__parameters:
    # 阿克曼小车参数
    wheelbase: 0.5                # 轴距（米）
    max_steering_angle: 0.4       # 减小转向角，更保守

    # 运动参数
    min_linear_vel: 0.05          # 更小的最小速度
    linear_acc_lim: 0.2           # 更小的加速度，更平滑
    steering_angle_velocity: 0.5  # 更小的转向速度

    # 安全参数
    simulate_ahead_time: 2.5      # 增大前瞻时间

# 行为树参数建议：
# forward_dist="0.75" backward_dist="1.0" max_speed="0.25" max_steering_angle="0.4"

# ============================================
# 激进配置 - 优先执行效率
# ============================================
# 特点：高速运行，快速完成
three_point_turn_recoveries_aggressive:
  ros__parameters:
    # 阿克曼小车参数
    wheelbase: 0.5                # 轴距（米）
    max_steering_angle: 0.7       # 增大转向角

    # 运动参数
    min_linear_vel: 0.15          # 增大最小速度
    linear_acc_lim: 1.0           # 增大加速度
    steering_angle_velocity: 2.0  # 增大转向速度

    # 安全参数
    simulate_ahead_time: 1.5      # 标准前瞻时间

# 行为树参数建议：
# forward_dist="0.75" backward_dist="1.0" max_speed="1.0" max_steering_angle="0.7"

# ============================================
# 参数调优指南
# ============================================
#
# 1. 轴距（wheelbase）
#    - 从车辆规格中获取准确值
#    - 过小：转弯半径计算不准
#    - 过大：掉头不完整
#
# 2. 最大转向角（max_steering_angle）
#    - 参考车辆实际最大转向角
#    - 过小：掉头空间需求大
#    - 过大：可能超出机械限制
#
# 3. 最小线速度（min_linear_vel）
#    - 接近目标时的最小速度
#    - 过小：执行时间过长
#    - 过大：精度降低
#
# 4. 线加速度限制（linear_acc_lim）
#    - 控制速度变化率
#    - 过小：响应慢，执行时间长
#    - 过大：运动不平滑
#
# 5. 转向角速度（steering_angle_velocity）
#    - 转向轮转动速度
#    - 过小：转向响应慢
#    - 过大：转向不平滑
#
# 6. 前瞻模拟时间（simulate_ahead_time）
#    - 碰撞检测的前瞻时间
#    - 过小：安全裕度不足
#    - 过大：过于保守，可能无法执行
#
# ============================================
